name: Welcome new contributors

on:  
  pull_request_target:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet first-time contributors
        uses: actions/first-interaction@v1
        with:
          pr-message: "Thanks for your first contribution! We're excited to have you here."
